name: CI_CD__Devices_Microservice

on:
  push:
    branches: [ IaC ]
    paths:      
      - '.github/workflows/Setup_PaaS.yml'
      - 'IaC/PaaS_Infra.ps1' 
  pull_request:
    branches: [ IaC ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Create_PaaS_Infra:
    runs-on: ubuntu-latest
    env:
      scriptPath: .github/workflows/Setup_PaaS.yml      
    steps:
    - uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: 'Run Setup PaaS powershell'
      shell: pwsh
      run: IaC/PaaS_Infra.ps1